spring:
  application:
    name: leave-balance
  datasource:
    url: jdbc:mysql://localhost:3306/leave_balance_manager
    username: supriyomondal
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    web: trace

server:
  port: 8082
