spring:
  kafka:
    bootstrap-server: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  application:
    name: employee-service
  datasource:
    url: jdbc:mysql://localhost:3306/employee_manager
    username: supriyomondal
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    web: trace


resilience4j:
  circuitbreaker:
    instances:
      getEmployee:
        register-health-indicator: true
        sliding-window-size: 5
        minimum-number-of-calls: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2
        automatic-transition-from-open-to-half-open-enabled: true
  retry:
    instances:
      getEmployee:
        max-attempts: 2
        retry-exceptions:
          - java.io.IOException
          - org.springframework.web.client.ResourceAccessException



