spring:
  application:
    name: employee-service
  datasource:
    url: jdbc:mysql://localhost:3306/employee_manager
    username: supriyomondal
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    web: trace

